<a href="https://colab.research.google.com/github/Desialvi/Especializacion_Data_Science/blob/main/Copia_de_numpy_ejercicios_clase.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ejercicios con numpy

#### Importar el paquete numpy usando como nombre np

In [2]:
import numpy as np

#### Crear un vector z de dimensión 10 inicializado en 0 

In [3]:
z= np.full((10,), 0)
print(z)

[0 0 0 0 0 0 0 0 0 0]


#### Crear un vector z de dimensión 10 inicializado en 0 pero con el quinto elemento siendo 1

In [4]:
z= np.full((10,), 0)
z[4]=1
print(z)

[0 0 0 0 1 0 0 0 0 0]


#### Crear un vector con valores entre 10 y 49 (inclusive) usando la función arange

In [15]:
z= np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### Invertir un vector (que el primer elemento sea el útltimo) (ayuda: usar slicing con paso negativo)

In [16]:
z = z[::-1]
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### Crear una matriz de 3x3 con valores entre 0 y 8 

In [10]:
b = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Dado el vector \[19,21,0,0,42,0,87,0,54,0\] devolver en nz un arreglo con los índices de aquellos componentes que sean distinto de 0 (usar la función nonzero)

In [18]:
v = [19,21,0,0,42,0,87,0,54,0]
nz = np.nonzero(v)
print(nz)

(array([0, 1, 4, 6, 8]),)


### Dado el vector [19,21,0,0,42,0,87,0,54,0] devolver en nz un arreglo con los índices de aquellos componentes que sean distinto de 0 (usar una list comprehension) ¿cuál es la diferencia con la celda anterior?

In [23]:
v2 = [19,21,0,0,42,0,87,0,54,0]
nz2 = [x for x in v2 if x != 0 ]
print(nz2)

[19, 21, 42, 87, 54]


### Dadas dos matrices, A (con dimensión 2x3) y B (con dimensión 2x2). Concatenarlas horizontalmente de forma tal que quede una matriz C de dimensiones 2x5 (buscar cuál es el comando correcto

In [33]:
A = np.random.random((2,3))
B = np.random.random((2,2))
C = np.concatenate((A,B), axis=1)
print (C)

[[0.76470097 0.25855739 0.62037665 0.73972208 0.24695387]
 [0.93588257 0.48536511 0.77530586 0.8585483  0.3411283 ]]


In [32]:
A = np.random.random((2,3))
B = np.random.random((2,2))
print(A)
print(B)

[[0.72401716 0.29935821 0.72410593]
 [0.65342993 0.40532545 0.80153912]]
[[0.93834141 0.65629758]
 [0.71711715 0.70020967]]


## Obtener un vector z1 que contenga la segunda fila de la matriz C

In [45]:
z1 = C[1,:]
print(z1, z1.shape)


[0.93588257 0.48536511 0.77530586 0.8585483  0.3411283 ] (5,)


### Obtener una matriz Z2 que contenga solamente la segunda fila de la matriz C


In [41]:
# matriz
Z2 = C[1:2, :] # tambien puede ser C[1::]
print(Z2, Z2.shape)

[[0.93588257 0.48536511 0.77530586 0.8585483  0.3411283 ]] (1, 5)


In [46]:
Z3 = C[1::]
print(Z3, Z3.shape)

[[0.93588257 0.48536511 0.77530586 0.8585483  0.3411283 ]] (1, 5)
